PaddleSprites:
     ;vert tile attr horiz
  .byte $67, $0A, $00, $70
  .byte $67, $0A, $00, $78
  .byte $67, $0A, $00, $80
  .byte $67, $0A, $00, $88

  .byte $7F, $0A, $00, $70
  .byte $7F, $0A, $00, $78
  .byte $7F, $0A, $00, $80
  .byte $7F, $0A, $00, $88

  .byte $97, $0A, $00, $70
  .byte $97, $0A, $00, $78
  .byte $97, $0A, $00, $80
  .byte $97, $0A, $00, $88

  .byte $AF, $0A, $00, $70
  .byte $AF, $0A, $00, $78
  .byte $AF, $0A, $00, $80
  .byte $AF, $0A, $00, $88

  .byte $C7, $0A, $00, $70
  .byte $C7, $0A, $00, $78
  .byte $C7, $0A, $00, $80
  .byte $C7, $0A, $00, $88
